services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - ~/.composer-docker/cache:/home/gd/.composer/cache
      - ./:/app
    ports:
      - 8000:80
    depends_on:
      - pgsql

  pgsql:
    image: postgis/postgis:17-3.5
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gd_challenge
      - POSTGRES_USER=gd
      - POSTGRES_PASSWORD=gd
    ports:
      - 5432:5432
  
volumes:
  pg-data:
